[2023-07-23T20:32:45.907+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_load_university_data.moving_old_files manual__2023-07-23T20:27:19.368671+00:00 [queued]>
[2023-07-23T20:32:45.925+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_load_university_data.moving_old_files manual__2023-07-23T20:27:19.368671+00:00 [queued]>
[2023-07-23T20:32:45.926+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-23T20:32:45.952+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): moving_old_files> on 2023-07-23 20:27:19.368671+00:00
[2023-07-23T20:32:45.965+0000] {standard_task_runner.py:57} INFO - Started process 2398 to run task
[2023-07-23T20:32:45.971+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'daily_load_university_data', 'moving_old_files', 'manual__2023-07-23T20:27:19.368671+00:00', '--job-id', '334', '--raw', '--subdir', 'DAGS_FOLDER/LoadInitiator.py', '--cfg-path', '/tmp/tmpclh27rq3']
[2023-07-23T20:32:45.976+0000] {standard_task_runner.py:85} INFO - Job 334: Subtask moving_old_files
[2023-07-23T20:32:46.099+0000] {task_command.py:410} INFO - Running <TaskInstance: daily_load_university_data.moving_old_files manual__2023-07-23T20:27:19.368671+00:00 [running]> on host 3906890fc071
[2023-07-23T20:32:46.211+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_load_university_data' AIRFLOW_CTX_TASK_ID='moving_old_files' AIRFLOW_CTX_EXECUTION_DATE='2023-07-23T20:27:19.368671+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-23T20:27:19.368671+00:00'
[2023-07-23T20:32:46.229+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-23T20:32:46.231+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/dags/MoveOldFilestoArchive.py']
[2023-07-23T20:32:46.263+0000] {subprocess.py:86} INFO - Output:
[2023-07-23T20:32:46.666+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-07-23T20:32:46.667+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.7/shutil.py", line 566, in move
[2023-07-23T20:32:46.668+0000] {subprocess.py:93} INFO -     os.rename(src, real_dst)
[2023-07-23T20:32:46.668+0000] {subprocess.py:93} INFO - OSError: [Errno 22] Invalid argument: '/opt/***/dags/data/RecievedData/Archived' -> '/opt/***/dags/data/RecievedData/Archived/Archived'
[2023-07-23T20:32:46.669+0000] {subprocess.py:93} INFO - 
[2023-07-23T20:32:46.669+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2023-07-23T20:32:46.670+0000] {subprocess.py:93} INFO - 
[2023-07-23T20:32:46.670+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-07-23T20:32:46.670+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/MoveOldFilestoArchive.py", line 25, in <module>
[2023-07-23T20:32:46.671+0000] {subprocess.py:93} INFO -     shutil.move(src_path_recieved, dst_path_recieved)
[2023-07-23T20:32:46.671+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.7/shutil.py", line 575, in move
[2023-07-23T20:32:46.672+0000] {subprocess.py:93} INFO -     " '%s'." % (src, dst))
[2023-07-23T20:32:46.672+0000] {subprocess.py:93} INFO - shutil.Error: Cannot move a directory '/opt/***/dags/data/RecievedData/Archived' into itself '/opt/***/dags/data/RecievedData/Archived/Archived'.
[2023-07-23T20:32:46.673+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-07-23T20:32:46.688+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-07-23T20:32:46.697+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_load_university_data, task_id=moving_old_files, execution_date=20230723T202719, start_date=20230723T203245, end_date=20230723T203246
[2023-07-23T20:32:46.717+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 334 for task moving_old_files (Bash command failed. The command returned a non-zero exit code 1.; 2398)
[2023-07-23T20:32:46.744+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-23T20:32:46.771+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
