[2023-07-23T20:27:33.373+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_load_university_data.loading_dbo manual__2023-07-23T20:27:19.368671+00:00 [queued]>
[2023-07-23T20:27:33.424+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_load_university_data.loading_dbo manual__2023-07-23T20:27:19.368671+00:00 [queued]>
[2023-07-23T20:27:33.425+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-23T20:27:33.443+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): loading_dbo> on 2023-07-23 20:27:19.368671+00:00
[2023-07-23T20:27:33.451+0000] {standard_task_runner.py:57} INFO - Started process 2252 to run task
[2023-07-23T20:27:33.455+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'daily_load_university_data', 'loading_dbo', 'manual__2023-07-23T20:27:19.368671+00:00', '--job-id', '325', '--raw', '--subdir', 'DAGS_FOLDER/LoadInitiator.py', '--cfg-path', '/tmp/tmpthb72lu1']
[2023-07-23T20:27:33.459+0000] {standard_task_runner.py:85} INFO - Job 325: Subtask loading_dbo
[2023-07-23T20:27:33.512+0000] {task_command.py:410} INFO - Running <TaskInstance: daily_load_university_data.loading_dbo manual__2023-07-23T20:27:19.368671+00:00 [running]> on host 3906890fc071
[2023-07-23T20:27:33.607+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_load_university_data' AIRFLOW_CTX_TASK_ID='loading_dbo' AIRFLOW_CTX_EXECUTION_DATE='2023-07-23T20:27:19.368671+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-23T20:27:19.368671+00:00'
[2023-07-23T20:27:33.613+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-23T20:27:33.613+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/dags/LoadDbo.py']
[2023-07-23T20:27:33.632+0000] {subprocess.py:86} INFO - Output:
[2023-07-23T20:27:33.949+0000] {subprocess.py:93} INFO - WARNING:root:Connection established to Postgres succussfully!....
[2023-07-23T20:27:33.966+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-07-23T20:27:33.966+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/LoadDbo.py", line 46, in <module>
[2023-07-23T20:27:33.967+0000] {subprocess.py:93} INFO -     pgcursor.execute(sql)
[2023-07-23T20:27:33.967+0000] {subprocess.py:93} INFO - psycopg2.errors.SyntaxError: syntax error at or near ")"
[2023-07-23T20:27:33.967+0000] {subprocess.py:93} INFO - LINE 1: ...NOT EXISTS (SELECT * FROM dbo.dim_university_data))         ...
[2023-07-23T20:27:33.967+0000] {subprocess.py:93} INFO -                                                              ^
[2023-07-23T20:27:33.968+0000] {subprocess.py:93} INFO - 
[2023-07-23T20:27:33.976+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-07-23T20:27:33.988+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-07-23T20:27:33.993+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_load_university_data, task_id=loading_dbo, execution_date=20230723T202719, start_date=20230723T202733, end_date=20230723T202733
[2023-07-23T20:27:34.007+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 325 for task loading_dbo (Bash command failed. The command returned a non-zero exit code 1.; 2252)
[2023-07-23T20:27:34.028+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-23T20:27:34.055+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
